[project]
name = "grammarlily"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "groq>=0.13.1",
    "streamlit>=1.41.1",
]
